[package]
name = "cargo-ex"
version = "0.1.0"
edition = "2021"
description = "This cargo sub-command execute `cargo run --example` easily via fuzzy finder."
authors = ["aoki <aoki@aoki.dev>"]
license = "MIT"

[dependencies]
anyhow = "1.0.56"
skim = "0.9.4"
